Pjanalista_DosCrucez/Models/ConsumidorModel.cs
namespace Pjanalista_DosCrucez.Models
{
    public class ConsumidorModel
    {
        public int IdConsumidor { get; set; }
        public string NombreConsumidor { get; set; }
        public string ApellidoConsumidor { get; set; }
        public string DireccionConsumidor { get; set; }
        public string CorreoElectronicoConsumidor { get; set; }
        public string DuiConsumidor { get; set; }
        public string ActivoConsumidor { get; set; }
    }
}

Pjanalista_DosCrucez/Models/EmpleadoModel.cs
namespace Pjanalista_DosCrucez.Models
{
    public class EmpleadoModel
    {
        public int IdEmpleado { get; set; }
        public string NombreEmpleado { get; set; }
        public string ApellidoEmpleado { get; set; }
        public string UsuarioEmpleado { get; set; }
        public string PasswordEmpleado { get; set; }
    }
}

Pjanalista_DosCrucez/Models/ErrorViewModel.cs
namespace Pjanalista_DosCrucez.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Pjanalista_DosCrucez/Models/JoinedModels.cs
namespace Pjanalista_DosCrucez.Models
{
    public class JoinedModels
    {
        public List<ReclamosModel> ReclamosJoined{ get; set; }
        public List<ConsumidorModel> ConsumidorJoined { get; set; }
    }
}

Pjanalista_DosCrucez/Models/ReclamosModel.cs
using System.ComponentModel.DataAnnotations;

namespace Pjanalista_DosCrucez.Models
{
    public class ReclamosModel
    {
        public int IdReclamo {  get; set; }
        
        [Required(ErrorMessage = "Este campo es obigatorio")]
        public string NombreProveedor {  get; set; }

        [Required(ErrorMessage = "Este campo es obigatorio")]
        public string DireccionProveedor {  get; set; }

        [Required(ErrorMessage = "Este campo es obigatorio")]
        public string TelefonoProveedor {  get; set; }

        [Required(ErrorMessage = "Este campo es obigatorio")]
        public string DetalleReclamo {  get; set; }

        [Required(ErrorMessage = "Este campo es obigatorio")]
        public string NombreConsumidor {  get; set; }

        [Required(ErrorMessage = "Este campo es obigatorio")]
        public string ApellidoConsumidor {  get; set; }
        public string EstadoReclamo {  get; set; }

        [Required(ErrorMessage = "Este campo es obigatorio")]
        public string EmailConsumidor {  get; set; }

        [Required(ErrorMessage = "Este campo es obigatorio")]
        public string DuiConsumidor {  get; set; }

        [Required(ErrorMessage = "Este campo es obigatorio")]
        public string DireccionConsumidor {  get; set; }

        [Required(ErrorMessage = "Este campo es obigatorio")]
        public double MontoReclamo {  get; set; }
        public DateTime FechaIngreso { get; set; }
        public DateTime FechaRevision { get; set; }
        public int IdEmpleado { get; set; }
        public int IdConsumidor { get; set; }
        public int IdEstado { get; set; }
        public bool activo { get; set; }


    }
}

Pjanalista_DosCrucez/Controllers/CiudadanoController.cs
using Microsoft.AspNetCore.Mvc;
using Pjanalista_DosCrucez.DataInfo;
using Pjanalista_DosCrucez.Models;

namespace Pjanalista_DosCrucez.Controllers
{
    public class CiudadanoController : Controller
    {
        ReclamosDatos _reclamosDatos = new ReclamosDatos();

        public IActionResult RegistrarReclamo(ReclamosModel oReclamos)
        {
            //if (!ModelState.IsValid)
            //    return View();

                var respuesta = _reclamosDatos.GuardarReclamo(oReclamos);

                if (respuesta)
                    return RedirectToAction("Index", "Home");
                else
                    return View();
        }
    }
}

Pjanalista_DosCrucez/Controllers/EmpleadoController.cs
using Microsoft.AspNetCore.Mvc;
using Pjanalista_DosCrucez.DataInfo;
using Pjanalista_DosCrucez.Models;
using System.Data.SqlClient;
using System.Data;

namespace Pjanalista_DosCrucez.Controllers
{
    public class EmpleadoController : Controller
    {
        ReclamosDatos _reclamosDatos = new ReclamosDatos();
        public IActionResult ListarReclamos()
        {
            var oLista = _reclamosDatos.listarReclamos();
            return View(oLista);
        }
        [HttpPost]
        public IActionResult ClasificarReclamos(ReclamosModel oReclamos)
        {
            var respuesta = _reclamosDatos.GuardarReclamo(oReclamos);

            if (respuesta)
                return RedirectToAction("ListarReclamos");
            return View();
        }
        public IActionResult LoginEmpleado()
        {
            return View();
        }
        [HttpPost]
        public IActionResult LoginEmpleado(EmpleadoModel oEmpleado)
        {
            bool exists = false;
            if(oEmpleado.UsuarioEmpleado != null)
            {
                exists = _reclamosDatos.verificarUsuario(oEmpleado.UsuarioEmpleado, oEmpleado.PasswordEmpleado);
                if (exists) {
                    return RedirectToAction("ListarReclamos");
                }
            }
            return View();
        }
        public IActionResult ClasificarReclamo()
        {
            return View();
        }
        [HttpPost]
        public IActionResult ClasificarReclamo(int idReclamo)
        {
            var oContacto = _reclamosDatos.buscarReclamo(idReclamo);
            return View(oContacto);
        }
        public IActionResult VerDetalleReclamo()
        {
            return View();
        }
        [HttpPost]
        public IActionResult VerDetalleReclamo(int idReclamo)
        {
            var oContacto = _reclamosDatos.buscarReclamo(idReclamo);
            return View(oContacto);
        }
    }
}

Pjanalista_DosCrucez/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Pjanalista_DosCrucez.Models;
using System.Diagnostics;

namespace Pjanalista_DosCrucez.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Pjanalista_DosCrucez/Views/Ciudadano/RegistrarReclamo.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model ReclamosModel 


@{
}
<div class="card">
    <div class="card-header">
        <h1>Clasificar Reclamo</h1>
    </div>
    <div class="card-body">
    <form asp-action = "RegistrarReclamo" asp-controller="Ciudadano" method="post">
         <div class="row mb-3">
            <h2>Datos Generales del Reclamo</h2>
        </div>
        <div class="row mb-3">
            <label for="txtProveedor" class="col-sm-2 col-form-label">Proveedor</label>
            <div class="col-sm-10">
                <input asp-for = "NombreProveedor" type="text" class="form-control" id="txtProveedor">
                <span asp-validation-for = "NombreProveedor" class ="text-danger"></span>
            </div>
        </div>
        <div class="row mb-3">
            <label for="txtDireccionProveedor" class="col-sm-2 col-form-label">Direccion</label>
            <div class="col-sm-10">
                    @Html.TextAreaFor(m => m.DireccionProveedor, 10, 40, new { @class = "form-control required"})
                     <span asp-validation-for = "DireccionProveedor" class ="text-danger"></span>
            </div>
        </div>
        <div class="row mb-3">
            <label for="txtDetalleReclamo" class="col-sm-2 col-form-label">Detalle del Reclamo</label>
            <div class="col-sm-10">
                    @Html.TextAreaFor(m => m.DetalleReclamo, 10, 40, new { @class = "form-control required" })
                    <span asp-validation-for = "DetalleReclamo" class ="text-danger"></span>
                </div>
        </div>
        <div class="row mb-3">
            <label for="txtTelefonoProveedor" class="col-sm-2 col-form-label">Teléfono</label>
            <div class="col-sm-10">
                <input asp-for = "TelefonoProveedor" type="text" class="form-control" id="txtTelefonoProveedor">
                <span asp-validation-for = "TelefonoProveedor" class ="text-danger"></span>

            </div>
        </div>
        <div class="row mb-3">
            <label for="txtMontoReclado" class="col-sm-2 col-form-label">Monto Reclamado</label>
            <div class="col-sm-10">
                    <input asp-for="MontoReclamo" type="text" class="form-control" id="txtMontoReclado">
                    <span asp-validation-for = "MontoReclamo" class ="text-danger"></span>
            </div>
        </div>
        <hr />
        <div class="row mb-3">
        <h2>Datos Generales del Consumidor</h2>
        </div>
        <div class="row mb-3">
            <label for="NombreConsumidor" class="col-sm-2 col-form-label">Nombres</label>
            <div class="col-sm-10">
                <input asp-for = "NombreConsumidor" type="text" class="form-control" id="txtNombreConsumidor">
                <span asp-validation-for = "NombreConsumidor" class ="text-danger"></span>
            </div>
        </div>
        <div class="row mb-3">
            <label for="ApellidoConsumidor" class="col-sm-2 col-form-label">Apellidos</label>
            <div class="col-sm-10">
                <input asp-for = "ApellidoConsumidor" type="text" class="form-control" id="txtApellidoConsumidor">
                <span asp-validation-for = "ApellidoConsumidor" class ="text-danger"></span>
            </div>
        </div>
        <div class="row mb-3">
            <label for="EmailConsumidor" class="col-sm-2 col-form-label">Correo Electrónico</label>
            <div class="col-sm-10">
                <input asp-for = "EmailConsumidor" type="email" class="form-control" id="txtEmailConsumidor">
                <span asp-validation-for = "EmailConsumidor" class ="text-danger"></span>
            </div>
        </div>
        <div class="row mb-3">
            <label for="EmailConsumidor" class="col-sm-2 col-form-label">Correo Electrónico</label>
            <div class="col-sm-10">
                <input asp-for = "DireccionConsumidor" type="email" class="form-control" id="txtEmailConsumidor">
                <span asp-validation-for = "DireccionConsumidor" class ="text-danger"></span>
            </div>
        </div>
        <div class="row mb-3">
            <label for="duiConsumidor" class="col-sm-2 col-form-label">DUI</label>
            <div class="col-sm-10">
                <input asp-for = "DuiConsumidor" type="text" class="form-control" id="txtDuiConsumior" onkeypress="return (event.charCode >= 48 && event.charCode <= 57)" maxlenght = "10">
                <span asp-validation-for = "DuiConsumidor" class ="text-danger"></span>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Guardar</button>
 

    </form>
    </<div>
 </div>

Pjanalista_DosCrucez/Views/Empleado/ClasificarReclamos.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="card">
    <div class="card-header">
        <h1>Clasificar Reclamo</h1>
    </div>
    <div class="card-body">
    <form>
        <div class="row mb-3">
        
        </div>
        <div class="row mb-3">
            <h2>Datos Generales del Reclamo</h2>
        </div>
        <div class="row mb-3">
            <label for="txtProveedor" class="col-sm-2 col-form-label">Proveedor</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="txtProveedor">
            </div>
        </div>
        <div class="row mb-3">
            <label for="txtDireccionProveedor" class="col-sm-2 col-form-label">Direccion</label>
            <div class="col-sm-10">
                <texarea class="form-control" id="txtDireccionProveedor"></texarea>
            </div>
        </div>
        <div class="row mb-3">
            <label for="txtDetalleReclamo" class="col-sm-2 col-form-label">Detalle del Reclamo</label>
            <div class="col-sm-10">
                <texarea class="form-control" id="txtDetalleReclamo"></texarea>
            </div>
        </div>
        <div class="row mb-3">
            <label for="txtTelefonoProveedor" class="col-sm-2 col-form-label">Proveedor</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="txtTelefonoProveedor">
            </div>
        </div>
        <div class="row mb-3">
            <label for="txtMontoReclado" class="col-sm-2 col-form-label">Monto Reclamado</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="txtMontoReclado">
            </div>
        </div>
        <hr />
        <div class="row mb-3">
        <h2>Datos Generales del Consumidor</h2>
        </div>
        <div class="row mb-3">
            <label for="NombreConsumidor" class="col-sm-2 col-form-label">Nombres</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="txtNombreConsumidor">
            </div>
        </div>
        <div class="row mb-3">
            <label for="ApellidoConsumidor" class="col-sm-2 col-form-label">Apellidos</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="txtApellidoConsumidor">
            </div>
        </div>
        <div class="row mb-3">
            <label for="EmailConsumidor" class="col-sm-2 col-form-label">Correo Electrónico</label>
            <div class="col-sm-10">
                <input type="email" class="form-control" id="txtEmailConsumidor">
            </div>
        </div>
        <div class="row mb-3">
            <label for="duiConsumidor" class="col-sm-2 col-form-label">DUI</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="txtDuiConsumior">
            </div>
        </div>
        
        <div class="row mb-3">
            <label for="EstadoReclamo" class="col-sm-2 col-form-label">Tipo de Atención</label>
            <div class="col-sm-10">
                <select class="form-select">
                    <option value="1">One</option>
                </select>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
    </div>
</div>

Pjanalista_DosCrucez/Views/Empleado/ListarReclamos.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model List<ReclamosModel>
<div class="card-header">
    <h1>Consulta de Reclamos</h1>
</div>
<div class="card-body">
    <table class="table table-bordered"> 
        <thead>
            <tr>
                <th>Codigo Reclamo</th>
                <th>Proveedor</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model){
                <tr>
                    <td>@item.IdReclamo</td>
                    <td>@item.NombreProveedor</td>
                    <td><button class="btn btn-primary" asp-action="ClasificarReclamos" asp-controller="Empleado">Ver Detalle</button></td>
                </tr>
            }
        </tbody>
    </table>
</<div>

Pjanalista_DosCrucez/Views/Empleado/LoginEmpleado.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model EmpleadoModel

<div class="card">
    <div class="card-header">
        <h1>Login</h1>
    </div>
    <div class="card-body">
        <form method="post">
            <div class="row mb-3">
                <label for="UsuarioEmpleado" class="col-sm-2 col-form-label">Usuario</label>
                @Html.EditorFor(model => Model.UsuarioEmpleado, new { htmlAttributes = new { @class = "form-control" } })
                
            </div>
            <div class="row mb-3">
                <label for="PasswordEmpleado" class="col-sm-2 col-form-label">Contraseña</label>
                @Html.EditorFor(model => Model.PasswordEmpleado, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
            </div>
            <button type="submit" class="btn btn-primary">Entrar</button>
        </form>
    </div>
 </div>

Pjanalista_DosCrucez/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Pjanalista_DosCrucez/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pjanalista_DosCrucez</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Pjanalista_DosCrucez.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empleado" asp-action="LoginEmpleado">Portal Empleado</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ciudadano" asp-action="RegistrarReclamo">Portal Ciudadano</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Pjanalista_DosCrucez - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>